Repository AdobeDocs/commerce-events, pull requests merged in 2022-10, with the labels that each got.

#54 COMDOX-346: Update project files for gatsby-theme-aio 4.6.2
  .env.example
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/linters/.yaml-lint.yml
  .github/scripts/get-path-prefix.js
  .github/workflows/deploy.yml
  .github/workflows/github-pages.yml
  .github/workflows/test-pull-request.yml
  .gitignore
  .yarn/releases/yarn-3.2.2.cjs
  .yarnrc.yml
  gatsby-ssr.js
  package.json
  yarn.lock
Labels: dependencies

#55 CEXT-934 - Add docs for event field data minimization
  src/pages/events/commands.md
  src/pages/events/module-development.md
Labels: Editorial

#65 Update theme, link checker, yarn
  .github/workflows/test-pull-request.yml
  .yarn/releases/yarn-3.2.2.cjs
  .yarn/releases/yarn-3.2.4.cjs
  .yarnrc.yml
  package-lock.json
  package.json
  yarn.lock
Labels: bug, dependencies
