Repository AdobeDocs/commerce-events, pull requests merged in 2023-05, with the labels that each got.

#128 Add autodeployment
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: enhancement

#131 Convert add-to-project-board to reusable workflow
  .github/workflows/add-to-project-board.yml
Labels: enhancement, maintenance

#134 1.2.0 release notes
  src/pages/get-started/release-notes.md
Labels: major update, internal
