Repository AdobeDocs/commerce-events, pull requests merged in 2023-02, with the labels that each got.

#99 Add indexing workflow
  .github/workflows/index.yml
Labels: enhancement

#100 Add V1.0.1 info
  src/pages/get-started/installation.md
  src/pages/get-started/module-development.md
  src/pages/get-started/release-notes.md
Labels: major update

#102 Upgrade theme and gatsby
  package.json
  yarn.lock
Labels: maintenance

#101 CEXT-1499: Add Cloud configuration for message queues
  src/pages/get-started/commands.md
  src/pages/get-started/configure-commerce.md
Labels: major update
