Repository AdobeDocs/commerce-events, pull requests merged in 2023-04, with the labels that each got.

#111 COMDOX-596: Update gatsby-theme-aio to 4.9.0
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: dependencies, maintenance

#117 fix linting error
  src/pages/get-started/configure-commerce.md
Labels: bug, editorial, internal

#114 CEXT-1599: Fix conversion of the nested array of objects
  src/pages/get-started/module-development.md
Labels: technical, internal

#122 V1.1.0 release notes
  src/pages/get-started/release-notes.md
Labels: major update, internal

#116 Merge: v1-develop into main
  src/pages/get-started/commands.md
  src/pages/get-started/configure-commerce.md
  src/pages/get-started/module-development.md
  src/pages/get-started/release-notes.md
Labels: maintenance, internal
